### ISSUE TITLE
Properties: Show/Hide

### ISSUE THREAD

**Issue by brunobellmann** [kodaagit/WebUebung#10]
Musst mal schauen was zu tun ist, ist iwie nicht wirklich beschreiben, vllt in den Fehlercodes nochmal schauen

denke showen und hiden von spalten halt aber würde iwie nicht so viel sinn ergeben wenn wir gesamte properties betrachen... dk

**Comment by AdrianGollmann** [comment]
Aus und Einblenden geht. Aber in KOmbi mit den anderen Funktionen ist das noch weird.
